name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Ensure to match the version you're using

    - name: Install dependencies
      run: |
        npm install -g aws-cdk  # Install AWS CDK globally
        npm install              # Install project dependencies

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::131332286832:role/githubdeployrole
        aws-region: us-east-1
        audience: sts.amazonaws.com

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name eksdemo

    - name: CDK Synth
      run: npx cdk synth

    - name: CDK Deploy
      run: npx cdk deploy --require-approval never
      env:
        OIDC_PROVIDER_ARN: arn:aws:iam::131332286832:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/883752FFF3EFBDB7B44543F17F0C3358
        KUBECTL_ROLE_ARN: arn:aws:iam::131332286832:role/kubectlrole

    - name: Apply Kubernetes manifests
      run: kubectl apply -f manifests/ -n aws-otel-eks
